ftphp:
  port: 2121
  # Search NMAP Signatures for server you would like to mimic
  banner: Fucking Twisted Python Honey Pot
  allow_login: true # If True, creates virtual filesystem. Otherwise captures login only.
  allow_anonymous: true
  restrict_login: true # Whether to use passwd or allow all logins
  pass_file: passwd # Password file to use if allow_login is true
  root: root # Directory of files to use for honeypot

logging:
  level: 0
  logfile: ./ftphp.log