# Don't touch these... for config parsing
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null  
  run:  
    dir: .

# Start of Main Configuration
ftphp:
  port: 2121
  # Search NMAP Signatures for server you would like to mimic
  banner: Fucking Twisted Python Honey Pot
  allow_login: true # If True, creates virtual filesystem. Otherwise captures login only.
  allow_anonymous: true
  restrict_login: false # Whether to use passwd or allow all logins
  pass_file: passwd # Password file to use if allow_login is true
  root: root # Directory of files to use for honeypot

logging:
  loglevel: INFO # Default to INFO
  logfile: ftphp.log
  format: "%(asctime)s %(levelname)s: %(message)s"
  datefmt: "%d.%m.%Y %H:%M:%S"